server_normal_Flask/routes/routes_todo.py
from utils import log
from routes import (
    login_required,
    current_user,
)

from flask import (
    request,
    Blueprint,
    render_template,
    redirect,
    url_for,
    session,
    make_response,
    abort,
)

from models.to_be_mongo import change_time
from models.todo import Todo
import time
from config import gg


main = Blueprint('todo', __name__)


@main.route('/index', methods=['GET'])
@login_required
def index():
    """
    显示该用户所有todo
    :return: 显示todo页面
    """
    user = current_user()
    todo_list = Todo.find_all(user_id=user.id, deleted=False)
    # 用字典对每个todo进行token和user.id的匹配
    # 保证每次调用index函数时清空gg
    gg.delete_value()
    # 保证每次调用index函数时都有新的token可用
    gg.set_value(user.id)
    log('from todo', gg.csrf_tokens, gg.token)
    body = render_template('todo_index.html', todos=todo_list, token=gg.token)
    return make_response(body)


@main.route('/add', methods=['POST'])
@login_required
def add():
    """
    添加todo
    :return: 返回index页面
    """
    user = current_user()
    form = request.form
    token = request.args.get('token')
    if Todo.check_token(token, gg.csrf_tokens):
        t = Todo.new(form, user_id=user.id)
        return redirect(url_for('.index'))


@main.route('/edit/<int:todo_id>', methods=['GET'])
@login_required
def edit(todo_id):
    # todo_id = int(request.args.get('id'))
    t = Todo.find_by(id=todo_id)
    user = current_user()
    if user.id != t.user_id:
        return redirect(url_for('.index'))
    token = request.args.get('token')
    if Todo.check_token(token, gg.csrf_tokens):
        body = render_template('todo_edit.html', t=t, token=token)
        return make_response(body)


@main.route('/update', methods=['POST'])
@login_required
def update():
    form = request.form
    token = request.args.get('token')
    if Todo.check_token(token, gg.csrf_tokens):
        Todo.check_id(form)
        newTodo = Todo.update(form)
        return redirect(url_for('.index'))


@main.route('/delete/<int:todo_id>', methods=['GET'])
@login_required
def delete(todo_id):
    # todo_id = int(request.args.get('id'))
    token = request.args.get('token')
    if Todo.check_token(token, gg.csrf_tokens):
        Todo.check_id(id=todo_id)
        Todo.remove(todo_id)
        return redirect(url_for('.index'))


# todo 修改
@main.route('/status_switch/<int:todo_id>', methods=['GET'])
@login_required
def switch(todo_id):
    # todo_id = int(request.args.get('id'))
    token = request.args.get('token')
    if Todo.check_token(token, gg.csrf_tokens):
        Todo.check_id(id=todo_id)
        status = request.args.get('status')
        t = Todo.complete(todo_id, status)
        return redirect(url_for('.index'))

server_normal_Flask/routes/routes_todo_ajax.py
from utils import log
from routes import (
    login_required,
    current_user,
)
from flask import (
    request,
    Blueprint,
    redirect,
    url_for,
    session,
    jsonify,
)
from models.todo import Todo
import time


main = Blueprint('ajax_todo', __name__)


@main.route('/index', methods=['GET'])
@login_required
def index():
    """
    显示该用户所有todo
    :return: 显示todo页面
    """
    user = current_user()
    todos = Todo.find_all_json(user_id=user.id, deleted=False)
    return jsonify(todos)


@main.route('/add', methods=['POST'])
@login_required
def add():
    """
    添加todo
    :return: 返回index页面
    """
    user = current_user()
    form = request.json
    t = Todo.new(form, user_id=user.id)
    return jsonify(t.json())


@main.route('/delete/<int:todo_id>', methods=['GET'])
@login_required
def delete(todo_id):
    # todo_id = int(request.args.get('id'))
    Todo.check_id(id=todo_id)
    Todo.remove(todo_id)
    t = Todo.find_by(id=todo_id)
    return jsonify(t.json())


@main.route('/update', methods=['POST'])
@login_required
def update():
    form = request.get_json()
    Todo.check_id(form)
    newTodo = Todo.update(form)
    return jsonify(newTodo.json())


# todo, status可否再作为一个动态路由里面的参数？
@main.route('/status_switch/<int:todo_id>', methods=['GET'])
@login_required
def switch(todo_id):
    # todo_id = int(request.args.get('id'))
    Todo.check_id(id=todo_id)
    status = request.args.get('status')
    t = Todo.complete(todo_id, status)
    return jsonify(t.json())

server_normal_Flask/routes/routes_tweet_ajax.py
from models.user import User
from models.tweet import Tweet

from utils import log

from flask import (
    request,
    Blueprint,
    redirect,
    url_for,
    session,
    jsonify,
)
from routes import (
    login_required,
    current_user,
)

main = Blueprint('ajax_tweet', __name__)


@main.route('/index', methods=['GET'])
@login_required
def index():
    user_id = int(request.args.get('user_id', -1))
    if user_id == -1:
        u = current_user()
        user_id = u.id
    user = User.find(user_id)
    tweets = Tweet.find_all_json(user_id=user.id, deleted=False)
    return jsonify(tweets)


@main.route('/add', methods=['POST'])
@login_required
def add():
    user = current_user()
    form = request.json
    t = Tweet.new(form, user_id=user.id, user_name=user.username)
    return jsonify(t.json())


@main.route('/delete/<int:tweet_id>', methods=['GET'])
@login_required
def delete(tweet_id):
    # tweet_id = int(request.args.get('id'))
    t = Tweet.find_by(id=tweet_id)
    Tweet.check_id(id=tweet_id)
    Tweet.remove(tweet_id)
    # 不管如何，都需要返回json的数据，为了触发ajax中回调函数
    return jsonify(t.json())


@main.route('/update', methods=['POST'])
@login_required
def update():
    form = request.get_json()
    Tweet.check_id(form)
    newTweet = Tweet.update(form)
    return jsonify(newTweet.json())


# route_dict = {
#     '/ajax/tweet/index': login_required(index),
#     '/ajax/tweet/add': login_required(add),
#     '/ajax/tweet/delete': login_required(delete),
#     '/ajax/tweet/update': login_required(update),
#     # 评论功能
#     '/ajax/comment/index': login_required(comment_index),
#     '/ajax/comment/add': login_required(comment_add),
#     '/ajax/comment/delete': login_required(comment_delete),
#     '/ajax/comment/update': login_required(comment_update),
# }

server_normal_Flask/templates/html_basic.html
<!DOCTYPE html>
<!-- html 中是所有的内容 -->
<html>
    <head>
        <meta charset="utf-8">
        <title>表单提交</title>
    </head>
    <body>
        <!-- html 中的空格是会被转义的, 所以显示的和写的是不一样的 -->
        <!-- 代码写了很多空格, 显示的时候就只有一个 -->
        很        好普通版
        <h1>很好 h1 版</h1>
        <h2>很好 h2 版</h2>
        <h3>很好 h3 版</h3>
        <!-- form 是用来给服务器传递数据的 tag -->
        <form action="{{ url_for('.message') }}" method="post">
            <textarea name="author" rows="8" cols="40"></textarea>
            <textarea name="message" rows="8" cols="40"></textarea>
            <!-- button type=submit 才可以提交表单 -->
            <button type="submit">POST 提交</button>
        </form>
        <form action="{{ url_for('.message') }}" method="get">
            <textarea name="author" rows="8" cols="40"></textarea>
            <textarea name="message" rows="8" cols="40"></textarea>
            <button type="submit">GET 提交</button>
        </form>
        <div>
            {% for m in messages %}
                <h3>{{ m }}</h3>
            {% endfor %}
        </div>
    </body>
</html>

server_normal_Flask/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册登录页面</title>
</head>
<body>
    <h1>登录</h1>
    <h2>你好 {{ username }}</h2>
    <form action="{{ url_for('.login') }}" method="post">
        <input type="text" name="username" value="aaa" placeholder="请输入用户名">
        <br>
        <input type="text" name="password" value="111" placeholder="请输入密码">
        <br>
        <button type="submit">登录</button>
    </form>

    <form action="{{ url_for('.out') }}" >
        <button type="submit">登出</button>
    </form>

    <h3>{{ result }}</h3>
    <!--方便调试-->
    <a href="{{ url_for('.profile') }}">My profile</a>
    <br>
    <a href="{{ url_for('todo.index') }}">My todos</a>
    <br>
    <a href="{{ url_for('ajax_todo.index') }}">My todos(ajax)</a>
    <br>
    <a href="{{ url_for('tweet.index') }}">My tweets</a>
    <br>
    <a href="{{ url_for('ajax_tweet.index') }}">My tweets(ajax)</a>
</body>
</html>

server_normal_Flask/templates/todo_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Todo index</title>
</head>
<body>
    <h1>TODO</h1>
    <h3>通过http的form添加</h3>
    <form action="{{ url_for('todo.add', token=token) }}" method="post">
        <input type="text" name="title" placeholder="请输入todo">
        <br>
        <button type="submit">添加</button>
    </form>
    <br>
    <h3>通过ajax的form添加</h3>
    <input id='id-input-todo' type="text" name="title" placeholder="请输入todo">
    <br>
    <button id='id-button-add'>添加</button>
    <div class="todo-list">
        <!--to_do will be here-->
        {% for t in todos %}
        <div class="todo-cell">
            <h3>{{ t.id }} : {{ t.title}}
                ct@{{ t.created_time }}
                ut@{{ t.updated_time }}
                完成? {{ t.status }}
                <a href="{{ url_for('todo.switch', todo_id=t.id, token=token) }}&status=True">设置为-完成</a>
                <a href="{{ url_for('todo.switch', todo_id=t.id, token=token) }}&status=False">设置为-未完成</a>
                <a href="{{ url_for('todo.edit', todo_id=t.id, token=token) }}">编辑</a>
                <a href="{{ url_for('todo.delete', todo_id=t.id, token=token) }}">删除</a></h3>
        </div>
        {% endfor %}
        <br>
        <br>
    </div>

    <script src="/static/Ajax_base.js"></script>
    <script src="/static/Ajax_todo.js"></script>
</body>
</html>

server_normal_Flask/templates/tweet_index.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>Tweet index</title>
</head>
<p>
    <h4>{{ user.username }}的Tweet</h4>

    <h3>去用户？的tweet</h3>
    <form name="go_to_user_form" action="{{ url_for('tweet.index') }}" method="get">
        <input class="go-to-user-input" name="user_id" value="-1" type="text" placeholder="输入用户id">
        <button class="go-to-user-button">GO</button>
    </form>
    <h4>通过http的form添加</h4>
    <a href="{{ url_for('tweet.new', token=token) }}">写新推特</a>
    <br>
    <h4>通过ajax的form添加</h4>
    <input id='id-input-tweet' type="text" name="title" placeholder="请输入tweet">
    <br>
    <button id='id-button-add'>添加</button>
    <br>
    <h3>http交互界面</h3>
    <div class="tweet-list">
        <h6>tweets</h6>
        {% for t in tweets %}
        {{ t.content }} from {{ user.username}} ct@{{ t.created_time}} ut@{{ t.updated_time}}
        <a href="{{ url_for('tweet.delete', tweet_id=t.id, token=token) }}">删除</a>
        <a href="{{ url_for('tweet.edit', tweet_id=t.id, token=token) }}">编辑</a>
        <h6>评论</h6>
        {% for c in t.comments() %}
        <div class="comment">
            {{ c.user().username }} : {{ c.content }}  ct@{{ c.created_time}} ut@{{ c.updated_time}}
        <a href="{{ url_for('comment.delete', comment_id=c.id, token=token) }}">删除</a>
        <a href="{{ url_for('comment.edit', comment_id=c.id, token=token) }}">编辑</a>
        </div>
        {% endfor %}
        <form action="{{ url_for('comment.add', token=token) }}" method="post">
            <input type="hidden" name="tweet_id" value="{{ t.id }}">
            <input name="content">
            <br>
            <button type="submit">添加评论</button>
        </form>
        {% endfor %}
        <h4>ajax交互界面</h4>
        <h6>tweets</h6>
    </div>

    <script src='/static/Ajax_base.js'></script>
    <script src='/static/Ajax_tweet.js'></script>
</body>
</html>